version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: us-central1-docker.pkg.dev/protean-mind-243117/my-docker-repo/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./json-output-files:/json-output-files
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontendnext
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/protean-mind-243117/my-docker-repo/frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontendnext:/frontendnext
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE=http://backend:8000
    depends_on:
      - backend
