steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/protean-mind-243117/my-docker-repo/backend:$COMMIT_SHA', 'backend']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/protean-mind-243117/my-docker-repo/backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/protean-mind-243117/my-docker-repo/backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--platform'
      - 'managed'
      - '--set-env-vars'
      - 'SUPABASE_URL=https://lucounujcuwuncxopbmq.supabase.co'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,GROQ_API_KEY=GROQ_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,SUPABASE_KEY=SUPABASE_KEY:latest'

images:
  - 'us-central1-docker.pkg.dev/protean-mind-243117/my-docker-repo/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

