-- Create a table to store daily quizzes
create table public.daily_quizzes (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  questions jsonb not null, -- Stores the list of 25 questions
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Ensure we only have one quiz per date (optional, but good for data integrity)
  constraint unique_date unique (date)
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table public.daily_quizzes enable row level security;

-- Policy: Allow anyone (anon) to READ data
create policy "Allow public read access"
on public.daily_quizzes
for select
to anon
using (true);

-- Policy: Allow service_role (our script) to INSERT/UPDATE data
create policy "Allow service_role to write"
on public.daily_quizzes
for all
to service_role
using (true)
with check (true);
